spring:
  application:
    name: single-app
  datasource:
    url: "jdbc:sqlite:${DB_PATH:/db/test.db}"
    # Cache size stands for a multiple of page size - 4096 bytes by default.
    # Setting 100 000 gives us  ~ 409,6MB of cache
    # We set it here, not in hikari.connection-init-sql,
    # because it (or SQLite) doesn't execute multiple PRAGMA statements.
    # See InitializingBean in the SingleApp class
    init-statements: >
      PRAGMA cache_size=100000;
      PRAGMA journal_mode=WAL;
      PRAGMA busy_timeout=5000;
    hikari:
      minimum-idle: 10
      maximum-pool-size: 10
      connection-timeout: 3000

  liquibase:
    change-log: classpath:liquibase/changelog.xml
  threads:
    virtual:
      enabled:
        true

server:
  port: 80

management:
  endpoints:
    web:
      exposure:
        include: [ "health", "info", "prometheus" ]