CREATE TABLE IF NOT EXISTS "user" (
    id UUID PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    version BIGINT NOT NULL
);

CREATE TABLE IF NOT EXISTS outbox_message (
    id UUID PRIMARY KEY,
    message JSONB NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    send_at TIMESTAMP NOT NULL DEFAULT NOW()
);