spring:
  application: project-service
  profiles:
    active: project
  threads:
    virtual:
      enabled: true
  jackson.deserialization.fail-on-missing-creator-properties: true

server:
  port: 8082

http-user-client.host: http://localhost:8081

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true