#!/bin/bash
export TEST_CASE="BATCH_INSERTS"
export QUERIES_TO_EXECUTE=${QUERIES_TO_EXECUTE:-2000}
export QUERIES_MAX_RATE=${QUERIES_MAX_RATE:-20}
export QUERIES_BATCH_SIZE=${QUERIES_BATCH_SIZE-500}
bash run_test_case.bash
