{
 "title": "Container",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "machine",
    "query": {
     "query": "label_values(collector_up_timestamp_seconds,machine)"
    }
   },
   {
    "name": "container",
    "query": {
     "query": "label_values(container_up_timestamp_seconds{machine=\"$machine\"},container)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Last Healthcheck",
   "type": "stat",
   "gridPos": { "h": 7, "w": 10, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_up_timestamp_seconds{machine=\"$machine\", container=\"$container\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - container_started_at_timestamp_seconds{machine=\"$machine\", container=\"$container\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "container_cpu_usage_percent{machine=\"$machine\", container=\"$container\"} / container_cpus_available{machine=\"$machine\", container=\"$container\"}",
     "legendFormat": "CPU usage"
    }
   ]
  },
  {
   "title": "CPUs used vs limit",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "container_cpu_usage_percent{machine=\"$machine\", container=\"$container\"}",
     "legendFormat": "CPUs used"
    },
    {
     "expr": "container_cpus_available{machine=\"$machine\", container=\"$container\"}",
     "legendFormat": "CPUs available"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "container_used_memory_bytes{machine=\"$machine\", container=\"$container\"} / container_max_memory_bytes{machine=\"$machine\", container=\"$container\"}",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "Memory used vs limit",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_used_memory_bytes{machine=\"$machine\", container=\"$container\"}",
     "legendFormat": "Memory used"
    },
    {
     "expr": "container_max_memory_bytes{machine=\"$machine\", container=\"$container\"}",
     "legendFormat": "Memory limit"
    }
   ]
  },
  {
   "title": "Logs events",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 6, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum by(machine, container, level) (increase(container_logs_total{machine=\"$machine\", container=\"$container\"}[1m]))",
     "legendFormat": "{{level}}"
    },
    {
     "expr": "sum by(machine, container) (increase(container_logs_total{machine=\"$machine\", container=\"$container\"}[1m]))",
     "legendFormat": "all"
    }
   ]
  }
 ]
}