spring:
  application:
    name: htmx-production-setup-app
  datasource:
    url: "${DB_URL:jdbc:postgresql://localhost:5432/htmx_db}"
    username: "${DB_USER:htmx_app}"
    password: "${DB_PASSWORD}"
    hikari:
      minimum-idle: 10
      maximum-pool-size: 10
  liquibase:
    change-log: classpath:liquibase/changelog.xml
  threads:
    virtual:
      enabled: true
  web:
    resources: # Static resources
      static-locations: [ "classpath:static" ]
      cache:
        # 1 year
        period: 31536000
server:
  port: "${SERVER_PORT:8080}"
  error:
    whitelabel.enabled: false
    path: "/error"

management:
  endpoints:
    web:
      exposure:
        include: [ "health", "info", "prometheus" ]


auth:
  issuer: htmx-production-setup
  token-key: "${AUTH_TOKEN_KEY}"
  token-duration: "PT48H"
  issue-new-token-before-expiration-duration: "PT45H"
