spring:
  application:
    name: htmx-production-setup-app
    #  datasource:
    #    url: "${DB_URL}"
    #    username: "${DB_USERNAME}"
    #    password: "${DB_PASSWORD}"
    pool-size: 5
  liquibase:
    change-log: classpath:liquibase/changelog.xml
  threads:
    virtual:
      enabled: true
  web:
    resources: # Static resources
      static-locations: [ "file:static" ]
      cache:
        period: 0
  devtools:
    restart:
      poll-interval: "1000ms"
      quiet-period: "500ms"

server:
  port: "${SERVER_PORT:8080}"
  whitelabel.enabled: false


management:
  endpoints:
    web:
      exposure:
        include: [ "health", "info", "prometheus" ]

auth:
  issuer: htmx-production-setup
  token-key: "qxg+hQ=="
  token-duration: "PT48H"
  issue-new-token-before-expiration-duration: "PT45H"



