spring:
  application:
    name: htmx-production-setup-app
    #  datasource:
    #    url: "${DB_URL}"
    #    username: "${DB_USERNAME}"
    #    password: "${DB_PASSWORD}"
    pool-size: 5
  liquibase:
    change-log: classpath:liquibase/changelog.xml
  threads:
    virtual:
      enabled: true
  web:
    resources: # Static resources
      static-locations: [ "file:static" ]
      cache:
        period: 0
         #1 year
#        period: 31536000
  devtools:
    restart:
      poll-interval: "1000ms"
      quiet-period: "500ms"

server:
  port: "${SERVER_PORT:8080}"

management:
  endpoints:
    web:
      exposure:
        include: [ "health", "info", "prometheus" ]




