#!/bin/bash
set -eu

export HOST="http://localhost:8080"
export REQUESTS=${REQUESTS:-500}
export REQUESTS_PER_SECOND=${REQUESTS_PER_SECOND:-50}
export MAX_CONCURRENCY=${MAX_CONCURRENCY:-100}
export VEMBEDDINGS_MODEL=${VEMBEDDINGS_MODEL:-"PERFORMANCE_TEST"}
export VEMBEDDINGS_DATA_SOURCE=${VEMBEDDINGS_DATA_SOURCE:-"PERFORMANCE_TEST"}

java LoadTest.java