spring:
  application:
    name: htmx-mpa-vs-react-spa
  web:
    resources: # for live reload from local, but outside the classpath dir
      static-locations: [ "file:static" ]
      cache:
        period: 0
#  datasource:
#    url: "${DB_URL:jdbc:postgresql://localhost:5432/analytics}"
#    username: "${DB_USERNAME:analytics}"
#    password: "${DB_PASSWORD:analytics}"
#    hikari:
#      minimum-idle: 1
#      maximum-pool-size: 5
  threads:
    virtual:
      enabled: true

server:
  port: 8080

html:
  css-path: "/live-styles.css"
  htmx-path: "/htmx.2.0.4.min.js"