spring:
  application:
    name: htmx-mpa-vs-react-spa
  web:
    resources: # for live reload from local, but outside the classpath dir
      static-locations: [ "file:static" ]
      cache:
        period: 0
  datasource:
    url: "${DB_URL:jdbc:sqlite:/tmp/htmx-vs-react.db}"
    sqlite:
      pool-size: 10
      busy-timeout: 500
      journal-mode: WAL
      # multiple of page size; default page size is 4096 bytes
      # https://www.sqlite.org/pragma.html#pragma_cache_size
      cache-size: 1000
  sql.init.mode: always
  threads:
    virtual:
      enabled: true

server:
  port: 8080

html:
  css-path: "/live-styles.css"
  htmx-path: "/htmx.2.0.4.min.js"