spring:
  application:
    name: htmx-mpa-vs-react-spa
  web:
    resources: # for live reload from local, but outside the classpath dir
      static-locations: [ "file:static" ]
      cache:
        period: 0
  datasource:
    url: "${DB_URL:jdbc:sqlite:/tmp/htmx-vs-react/htmx-vs-react.db}"
    hikari:
      minimum-idle: 10
      maximum-pool-size: 10
      connection-init-sql: >
        PRAGMA journal_mode=WAL;
        PRAGMA cache_size=-10000;
        PRAGMA temp_store=MEMORY;
        PRAGMA foreign_keys = ON;
  sql.init.mode: always
  threads:
    virtual:
      enabled: true

server:
  port: 8080

html:
  css-path: "/live-styles.css"
  htmx-path: "/htmx.2.0.4.min.js"